// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTEgzEy3Z6pxzLFo2F-5_kPVvzHwz3y7Q',
    appId: '1:535601089488:web:28eea586b7517ee78947d5',
    messagingSenderId: '535601089488',
    projectId: 'vtm-8559d',
    authDomain: 'vtm-8559d.firebaseapp.com',
    storageBucket: 'vtm-8559d.firebasestorage.app',
    measurementId: 'G-1TPHH43E5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfs1bEA1r5yOLDAAjboyD9JlcTxIGxsjQ',
    appId: '1:535601089488:android:d3ffc7cf73c117f58947d5',
    messagingSenderId: '535601089488',
    projectId: 'vtm-8559d',
    storageBucket: 'vtm-8559d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_SkkC0uRPIuH5Gyl6JD62YBpt1ITbcI',
    appId: '1:535601089488:ios:7d012926cc06d0e88947d5',
    messagingSenderId: '535601089488',
    projectId: 'vtm-8559d',
    storageBucket: 'vtm-8559d.firebasestorage.app',
    iosBundleId: 'com.example.vtm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_SkkC0uRPIuH5Gyl6JD62YBpt1ITbcI',
    appId: '1:535601089488:ios:7d012926cc06d0e88947d5',
    messagingSenderId: '535601089488',
    projectId: 'vtm-8559d',
    storageBucket: 'vtm-8559d.firebasestorage.app',
    iosBundleId: 'com.example.vtm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTEgzEy3Z6pxzLFo2F-5_kPVvzHwz3y7Q',
    appId: '1:535601089488:web:e9064410fecbb0788947d5',
    messagingSenderId: '535601089488',
    projectId: 'vtm-8559d',
    authDomain: 'vtm-8559d.firebaseapp.com',
    storageBucket: 'vtm-8559d.firebasestorage.app',
    measurementId: 'G-91N001GD73',
  );
}
